
export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_SIGNIN_RESET = "USER_SIGNIN_RESET";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";
export const USER_LOGOUT_RESET = "USER_LOGOUT_RESET";

export const USER_LOAD_REQUEST = "USER_LOAD_REQUEST";
export const USER_LOAD_SUCCESS = "USER_LOAD_SUCCESS";
export const USER_LOAD_FAIL = "USER_LOAD_FAIL";
export const USER_LOAD_RESET = "USER_LOAD_RESET";

export const USER_APPLY_JOB_REQUEST = "USER_APPLY_JOB_REQUEST";
export const USER_APPLY_JOB_SUCCESS = "USER_APPLY_JOB_SUCCESS";
export const USER_APPLY_JOB_FAIL = "USER_APPLY_JOB_FAIL";
export const USER_APPLY_JOB_RESET = "USER_APPLY_JOB_RESET";

export const ALL_USER_LOAD_REQUEST = "ALL_USER_LOAD_REQUEST";
export const ALL_USER_LOAD_SUCCESS = "ALL_USER_LOAD_SUCCESS";
export const ALL_USER_LOAD_FAIL = "ALL_USER_LOAD_FAIL";
export const ALL_USER_LOAD_RESET = "ALL_USER_LOAD_RESET";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";
export const USER_SIGNUP_RESET = "USER_SIGNUP_RESET";

export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILURE = "SEND_MESSAGE_FAILURE";
export const GET_MESSAGES_REQUEST = "GET_MESSAGES_REQUEST";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_FAILURE = "GET_MESSAGES_FAILURE";

export const APPROVE_USER_REQUEST = "APPROVE_USER_REQUEST";
export const APPROVE_USER_SUCCESS = "APPROVE_USER_SUCCESS";
export const APPROVE_USER_FAILURE = "APPROVE_USER_FAILURE";

export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS";
export const GET_USER_BY_ID_FAILURE = "GET_USER_BY_ID_FAILURE";
export const GET_USER_BY_ID_REQUEST = "GET_USER_BY_ID_REQUEST";

export const DELETE_JOB_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_JOB_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_JOB_FAILURE = 'DELETE_USER_FAILURE';

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const FETCH_APPROVER_SUCCESS = 'FETCH_APPROVER_SUCCESS';

